### ISSUE TITLE
Dúvida do youtube 

### ISSUE THREAD

**Issue by Mike-deep** [alisonpezzott/powerbi#1]
Boa noite, Alisson. Tudo bem?

Sou o Michel, sou de Jundiaí tbm. 
A dúvida que comento seria possivel realizar o gráfico em anexo no excel,
Utilizando as medidas personalizadas que seriam criadas no Power Pivot.

Caso, tenha disponibilidade poderia gravar um video.

![Medida personalizada em DAX](https://github.com/alisonpezzott/powerbi/assets/150087737/71855a2e-06ba-4549-9817-0eb8625b4d9f)

Desde já agradeço.

**Comment by alisonpezzott** [comment]
Boa noite, Michel

Não sei te dizer se é possível no Excel.

Sds
